### ISSUE TITLE
Parties Page

### ISSUE THREAD

**Issue by DInnoStudio** [adamosimpson21/wepollclient#1]
Priority : High

Add the Parties Page to the new site.  The layout of the old site is fine, where it just lists the parties in a series down the page.  After joining a party, you should be able to view and write on the party forum.  
For now anyone can enter and leave a party at will.  But eventually there will be control of access by the party heads.
For now we will only offer parties created by moderators.  But eventually party creation and governance will be possible with level/xp perks.

**Comment by adamosimpson21** [comment]
Difficulty: 3

I'll make it similar to the shop, where you can go and add parties and details in the client if you're an admin or founder, and then normal users will be able to join or leave parties at will

**Comment by adamosimpson21** [comment]
The forum aspect of this is very difficult and would require A LOT of work. It's possible we should outsource this portion to another site in the future. There are lots of services that will take care of the functionality for us, and then we just customize the styling and experience. I doubt this is something we want to build in house at the moment

**Comment by adamosimpson21** [comment]
Check what I've got on the live site so far and let me know what kind of polish I can put on it

**Comment by DInnoStudio** [comment]
The parties system works great, thanks!  
Yeah I assumed we would use another existing forum service.  What is the difficulty level of linking that and setting it up?  I have a forum on dinnostudio through some sort of widget.

**Comment by adamosimpson21** [comment]
I would say let it just be informal for now. Something like discord or slack could be set up by the party members themselves. Even a facebook group or w/e is going to be sufficient for quite some time. When we're getting more traffic we can look into out sourcing forums
