### ISSUE TITLE
Question Page layout 

### ISSUE THREAD

**Issue by DInnoStudio** [adamosimpson21/wepollclient#12]
Priority: High

On the Question page, change the text of "Look at all of these cool questions you can answer!" to "Represent yourself by answering the polls below!".
Also, make "You've answered all of the questions already? Why not create your own?
Create a new question" into it's own button, and have it at the bottom of the page, below all the polls, and change the text to "Want to ask a different question? Create a poll here!"

**Comment by adamosimpson21** [comment]
Sweet. This is really simple, I'll do it when I get home

**Comment by adamosimpson21** [comment]
Content fixes like this are really easy to implement and tweak, so feel free to throw them at me. If you have whole page layouts, they're the best because it gives me something to follow for all pieces of a view

**Comment by adamosimpson21** [comment]
done
