### ISSUE TITLE
Earning "coin"

### ISSUE THREAD

**Issue by DInnoStudio** [adamosimpson21/wepollclient#14]
Priority: Mid
Let's call our earned currency "Opinion Points" or "OP".
A new user is automatically given 20 OP.  They can earn more OP doing various tasks.
The first such task is to answer a poll.  After submitting an answer, they get 5 OP.  On the results page, it should tell the user "You earned 5 Opinion Points for answering that poll!" in a congratulatory yellow font.
So the issue here is to create the function of getting 5 OP after answering a poll, and alert the user.
(We can modify the exact numbers of OP earned in a few months after watching the data.)

**Comment by adamosimpson21** [comment]
When you say 'earned currency' I'm guessing this is soft currency? I feel like all currency is earned currency? 
 Difficulty : 1

**Comment by DInnoStudio** [comment]
Earned vs purchased.  Or soft vs hard.  Either way, you know what I mean.  Opinion points vs Influence points.  Thanks

**Comment by adamosimpson21** [comment]
So, adding the amount for each question is super easy, it's going to take me a little bit to set up the systems for the message, so this is half done?

**Comment by DInnoStudio** [comment]
I see that I'm getting coins, but not the message yet.  Good work, keep it up!

**Comment by adamosimpson21** [comment]
I was working on the message last night, should be ready today or tomorrow. I also improved the visuals of it a lot. There are many ways to do it, but I think the one I have is fine for the foreseeable future

**Comment by adamosimpson21** [comment]
Done
