### ISSUE TITLE
Results page text formatting

### ISSUE THREAD

**Issue by DInnoStudio** [adamosimpson21/wepollclient#15]
Priority: High
We need to adjust the formatting for the text on the results page.  Compress some of the paragraph spacing in the question, title, education, rating etc.  Also, the legend for the pie chart is too narrow, so the text drops down and pushes later answers off the page.  Please make it wider.

**Comment by adamosimpson21** [comment]
Pictures help a lot for these types of things, even just screen shots with arrows drawn in. Is there a particular question you're viewing which looks bad? These types of things also vary widely based on screen width. Something on a normal sized computer screen vs laptop vs mobile will look different. This can also be fixed through truncating the answers on the results page, especially if you have long answers

**Comment by adamosimpson21** [comment]
I adjusted a bunch of these elements, let me know how it looks

**Comment by DInnoStudio** [comment]
Much better, thanks!
