### ISSUE TITLE
Question page poll layout

### ISSUE THREAD

**Issue by DInnoStudio** [adamosimpson21/wepollclient#16]
Priority: Mid
The poll layout on the question page should be modified.  It should display the title (as it does), then, remove the display of the Description field, and instead place the first 75 characters of the Question field, in "Quotes", with elipses... if it's longer than 75 characters.  30 characters max per line, so max 3 lines of question.
i.e.
(centered)
Birthright Citizenship

"Regarding birthright 
citizenship, should the 14th 
Amendment be kept, removed, ..."

**Comment by adamosimpson21** [comment]
The description field isn't displayed. Most of the questions posted have the same description and question fields. The description should be short (Should we have birthright citizenship?) or shorter. If it's super long (as a lot of them are) they look kind of a mess. The question content is viewable on the question/ID page. 

Or are you talking about the View All question page? Check the URL for "/question" or "/question/questionID". Also, screenshots help a lot

That's really easy to fix

**Comment by adamosimpson21** [comment]
![image](https://user-images.githubusercontent.com/13780256/48053107-a965da00-e15e-11e8-8434-eb92f70f2ee0.png)

I can make it wider to fit in more characters, but I feel like just enforcing a shorter description is a better idea though. I feel like the description field is useful for the 'at a glance' view of a poll. I could definitely include better instructions on the 'create a question' page, but when used properly I feel like it's a useful tool for guiding users to the questions they want to answer. Imagine a scenario where a question reads "What part of the government do you think should regulate the taxation of..." gives a whole lot of fluff and no content of the question, but might be necessary for the full question. The title could be "Taxation of marijuana" and the description "Who controls the taxation of marijuana", etc, but the question content can be more verbose and explain the particulars and nuances of the question

**Comment by DInnoStudio** [comment]
I'm talking about the http://wepoll.herokuapp.com/question page.  Your screenshot captured it.  
The point is that the current layout is too lengthy and not serving its purpose on that page.  Either we enforce a 75 char description, or do the first 75 char of the Q and have the descrip on the Q specific page.

**Comment by adamosimpson21** [comment]
I'm enforcing the 75 character description, along with some other reasonable lengths for title, answers, etc. Let me know what you think. Very easy to change over time
