### ISSUE TITLE
Poll Results page new buttons needed

### ISSUE THREAD

**Issue by DInnoStudio** [adamosimpson21/wepollclient#19]
Priority: High

We need 2 new buttons on the poll results chart page.  Shown in green.  Questions page links back to the main Questions page.  Next poll! links to whatever poll is next in line on the Questions page.
Also shorten the pie chart and bar chart buttons.  And default to the pie chart.

![pollresultspg1](https://user-images.githubusercontent.com/32209073/48296231-538c7d00-e451-11e8-9550-1522ef490de4.jpg)

**Comment by adamosimpson21** [comment]
Most of this is trivial, but the "next poll" button is weirdly complicated. How do you decide what poll to take them to? I can do everything else easily (it's already done honestly,) but the next poll button is going to take some time to craft (not the layout for it, but the functionality)

**Comment by DInnoStudio** [comment]
Right now it doesn't really matter which poll it takes them to.  Later, when we have them sorted properly, this may be more complicated.  At the moment it can take them to any poll honestly, it's just a way to keep the user moving

**Comment by adamosimpson21** [comment]
Yea, I'll see what I can do It's just going to take me a minute to put all the pieces together

**Comment by adamosimpson21** [comment]
"done" but I can't get to test it until I get back to my computer

**Comment by adamosimpson21** [comment]
Ok, everything should be on heroku now
