### ISSUE TITLE
Mobile layout - parties page

### ISSUE THREAD

**Issue by DInnoStudio** [adamosimpson21/wepollclient#20]
Priority: High

Update UI on mobile - parties page.  Follow the sketch attached below.

![mobilepartiespage](https://user-images.githubusercontent.com/32209073/48296452-5046c080-e454-11e8-9213-de1b13c4013d.jpg)

**Comment by adamosimpson21** [comment]
The main thing I'm working on in mobile lay outs. Thanks for the image, though. I think the join party and learn more buttons should be under the picture, there really isn't enough space on mobile to make them fit on the side. I'll play with it and send back some screen shots

**Comment by adamosimpson21** [comment]
1:
![image](https://user-images.githubusercontent.com/13780256/48310262-f243d700-e540-11e8-957d-7cc8e3416efc.png)
 
2: 
![image](https://user-images.githubusercontent.com/13780256/48328066-1235d200-e5f7-11e8-8458-88c750be9762.png)



Obivously these are largely unstyled, if we're sure on a layout, I'll make it happen and make it prettier, but this is about the right dimensions for your average mobile phone

**Comment by DInnoStudio** [comment]
#1 is good, I see you've pushed that out to mobile.  It looks quite good, just two minor tweaks - the buttons "learn more..." and "join this party" should be the same format (shape, font, size, shadow) just different colors, and try to line them up better.  Also after the text description "we believe etc" please insert a blank line, so the light gray bubble goes a little further down past the text.  Thanks

**Comment by adamosimpson21** [comment]
Done
