### ISSUE TITLE
Fading Popup Messages

### ISSUE THREAD

**Issue by DInnoStudio** [adamosimpson21/wepollclient#21]
![message](https://user-images.githubusercontent.com/32209073/49121118-8cf42380-f26c-11e8-93b7-b66fbce62b64.jpg)
 
Priority: Low

Please make these messages fade after 10 seconds, if the user stays on the page that long, or disappear when the user moves to another page.  Thanks

**Comment by adamosimpson21** [comment]
10 seconds is a really long time, let's try 6 and see how it feels. Other part is done (not pushed to heroku yet

**Comment by DInnoStudio** [comment]
Sure, great.
