### ISSUE TITLE
User traffic data

### ISSUE THREAD

**Issue by DInnoStudio** [adamosimpson21/wepollclient#22]
Priority : Mid

An admin tool which lets me see some statistics about our users.  Number of users, lvl, OP, parties joined, etc.  And more traffic related statistics like daily traffic, page loads, user location, etc.  Thanks

**Comment by adamosimpson21** [comment]
Difficulty: 8-9. Also, these are kind of two separate issues. The first half of those are database statistics, which would require a content management system (CMS), which is pretty big undertaking, but could be a possible next step. 


The other half are website statistics and analytics, which would require a little bit of research and probably some type of investment ($), but I'll look into it and see if there's something easy we can do for it

**Comment by adamosimpson21** [comment]
According to the Database: 
37 users, 2 are me (real), 25 are me (fake/tests), 4 are you, and 6 other people (roughly)
42 questions
270 ballots cast (probably following the same distribution as the users)

**Comment by DInnoStudio** [comment]
Okay great.  This is a mid priority so lets not build the CMS yet.  6 real people is decent...  
The website analytics might be a simpler solution.  My other website uses webstat at the free level, can you use that?

**Comment by adamosimpson21** [comment]
I hooked into google analytics, so that should give us data from here on out. I haven't had any (non-me) people sign up in a while, but it's good to know it's working. I'm going to try and figure out how to share the analytics with you

**Comment by adamosimpson21** [comment]
what email should I send it to? A google one would probably be easiest

**Comment by DInnoStudio** [comment]
info@dinnostudio.com
