### ISSUE TITLE
Adding shop items 

### ISSUE THREAD

**Issue by DInnoStudio** [adamosimpson21/wepollclient#4]
Priority: High

Where can I add the shop items again?

**Comment by adamosimpson21** [comment]
Add them through the client. I haven't set up images yet, so just host them for the time being. Let me know if you need more options for the items, how they'd like to be displayed.

When you add them through the client, on the top form, it'll add them permanently. That's the admin changing the game form. The bottom is what a normal user would see, where they can choose from items and add them to their personal inventory. If you'd like to see the difference, the easiest way is to just make a dummy account to see what a normal user would see
