### ISSUE TITLE
Profile Demographics

### ISSUE THREAD

**Issue by DInnoStudio** [adamosimpson21/wepollclient#5]
Priority: Mid

Ability to answer demographic data to be shown on profile

**Comment by adamosimpson21** [comment]
Difficulty: 3

**Comment by adamosimpson21** [comment]
Working on this. Roughly 60% done

**Comment by adamosimpson21** [comment]
Should work pretty well. Let me know what I can do with it next time you check out the live build

**Comment by DInnoStudio** [comment]
Looks great! For gender, we don't need "Choose not to say" and "not specified".  Make the "choose not to say" into "neutral".  Otherwise it's perfect!

**Comment by adamosimpson21** [comment]
Done. You'll see the changes next time I push
