### ISSUE TITLE
Security Levels for Polls

### ISSUE THREAD

**Issue by DInnoStudio** [adamosimpson21/wepollclient#6]
Priority: Mid

We need to give the user the ability to select the privacy level of each poll response.
Secret - Eventually blockchain, but for now just top security level, no link to demo data, minimal info retained to know the user cast the poll.
Private - Secure poll response, but carries a link to demographic data and user's other question answers (at level private or public) that can be accessed later by analytical systems.  
Public - Secure poll response, also poll question and answer are displayed on a user's profile page, and carries a link to demographic data and user's other question answers (at level private or public) that can be accessed later by analytical systems.  

This selection choice should be shown on the same page where a user selects their poll response and submits it.  To the right of the poll, make a simple graphic in stop light form, with green for public, yellow for private, red for secret. Include the text title for each security level as well. Default is "Secret - Red".  A link below the graphic connects to an explanation of the security levels.

**Comment by adamosimpson21** [comment]
As it currently sits: Only the user ID is pair with the response. Each user has a set of demographics attached to them, but none of the demographics are attached to the response itself. It's relatively easy to never show a user's username through the results. I can attach demographic data easily, without ever giving the username. It's almost impossible completely obscure the user's ID through the developer's console. This is a security issue that can be dealt with down the road, and would take a long time to work on right now, and would have vastly decreased performance issues. (Essentially, you'd hide all of the information on the server, and then only reveal the final chart, but this is very difficult to do on a server, and would require a lot of requests and logic).

Difficulty: 4, but there are a lot of pieces at work here. Currently, there's no way to view someone else's profile page. You can't look up or find users, even if you know their ID or username. That's just not a feature I've built yet. It can be done, and pretty easily, but I don't think this feature is that necessary until we have user interaction

**Comment by DInnoStudio** [comment]
Okay.  So it sounds like the "secret" system is the existing system.  If they select "private" the question should get the demo data attached, as you described.  If they select "public" then can you have the Q result show on their profile page?
For now, users will not be able to see other people's profiles, only their own.

**Comment by adamosimpson21** [comment]
So the data is a lot more pliable than that. Everything is linked together. I don't need to save a result with or w/o demographic data. All I do is store the user's ID, and then I can choose to pull what data I need along with that. I can set up a filter for this so data won't be pulled during certain requests, but I feel we can get around this with a simple "WePoll will never store your username or party with your answer". Which is true, you just store a reference to that player, which you can't get around since you have to know if that user answered a question

**Comment by DInnoStudio** [comment]
Understood.  But we need to offer this security option to the users for each answer.  It's an important feature for the users.  It might not mean a whole lot, technically, now, but we need to establish the system and trust with the user.  In the future, as data management & security improves, it will mean more.

**Comment by adamosimpson21** [comment]
Ok. I'll make the buttons and give a little description in the short term, and build the system in a little bit

**Comment by adamosimpson21** [comment]
Also, I learned a lot about block chain and we should talk about the good use cases for it soon. It might have a place in WePoll, but not in the short term

**Comment by adamosimpson21** [comment]
The front-facing side of this is almost done, but the infrastructure hasn't been started yet. Can you write up some info to display to the user about what this is and why we have it? I'm going to put a little "What is this" box on the answer page that people can click, because they'll want to know which button to press for each answer.

**Comment by DInnoStudio** [comment]
"Poll Privacy 
For each poll you can choose the privacy level of your answer.  
(Red) Secret - Answer doesn't link to your other Answers, not shown on your profile.
(Yellow) Private - Answer is linked to your other Answers, but not shown on your profile.
(Green) Public - Answer is linked to your other Answers, and shown on your profile.

At private and public levels, data about your other private and public answers, including your demographic data, are linked to this poll answer, for statistical analysis purposes.  If a poll answer is public, it will appear on your public profile, visible to anyone able to view your profile."

**Comment by adamosimpson21** [comment]
Secret - Top security level, no demographic data or information about you is retained
           
Private - Secure poll response. Carries a link to demographic data that can be accessed later by analytical systems. Answer is linked to your other Answers.
            
Public - Secure poll response. Poll question and answer are displayed on a user's public profile page, and carries a link to demographic data that can be accessed later by analytical systems.

How about something like that? It's close to what you originally wrote, and I think it gives more information in a more efficient manner

**Comment by DInnoStudio** [comment]
Sure, looks great.
