### ISSUE TITLE
Analyze poll results

### ISSUE THREAD

**Issue by DInnoStudio** [adamosimpson21/wepollclient#8]
Priority: Mid

A button that reads "analyze" which displays along with the poll results after a user votes.
For now it can be an "inactive" link.
Later it will go to the "analyzer" page, where a user will be able to select multiple polls or demo and create complex charts.  This is a whole involved process that will require some assistance from a data analyst, statistician, etc.

**Comment by adamosimpson21** [comment]
So, you just want the button? That's really easy, but I'm worried it might confuse people who try and click it. I can add a Warning message that's like "Not Implemented yet, check back soon", but I don't see what kind of value that has at the moment. 
Difficulty: 1?

**Comment by DInnoStudio** [comment]
Yes please add it, with the "Not Implemented yet, check back soon" warning.  It's an important feature and something people are interested in.  
We need a way to start framing out how this section is going to work.  Can you describe a few of the tasks involved and their difficulty?

**Comment by adamosimpson21** [comment]
Ok. This is pretty easy once I get the base data visualization set up. I'm going to do some polishing of current features and then tackle that. The best way for you to help me with this is adding some more data to the site. Make a couple accounts and pick a question you'd like to analyzed, and answer it a couple times. I have dummy data on my development branch that I'll use for testing, but itll be hard to show it off with a large number of screen shots.

It doesn't even need to be a button to do this necessarily. It can be attached to the results page, and then have options on that same page. Incorporating the users demographic info is easy, and the filters are pretty easy as well. I'll make a little wire frame when I get home to show you how I think it'd look, if you want to draw one up I'd be happy to talk about designs

I think this is a great feature and has a lot of appeal to people, and it's be really awesome to show off, but it's not that exciting when 2-3 people have answered a poll. I think if we have a dummy question with mock data, it'd be a great way to show it off

**Comment by adamosimpson21** [comment]
Done. we still have the data scarcity issue, though
